# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: test tftp package
        run: go test github.com/oakdoor/go-tftp/tftp

      - name: test netascii package
        run: go test github.com/oakdoor/go-tftp/netascii

      - name: build server
        run: go build -o tftp-server cmd/tftp-server/main.go

      - name: build client
        run: go build -o tftp-client cmd/tftp-client/main.go

      - name: run end to end test
        run: ./test/cli_applications.sh

